

const LandingPage = () =>{
    return(
        <div>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
           <h1>Obi</h1>
        </div>
    )
}

export default LandingPage